core/urls.py
from django.urls import path
from django.contrib import admin
from .views import (
    HomeView,
    ProductDetailView,
    ProductCheckoutView,
    ProductPaymentView,
    ProductsView,
    OrderSummary,
    add_to_cart,
    remove_from_cart,
    remove_single_from_cart,
    AddCouponView,
    get_items_by_category,
    RefundRequestView,
    UserProfileView,
)

app_name = 'core'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('products/', ProductsView.as_view(), name='products'),
    path('order-summary/', OrderSummary.as_view(), name='order-summary'),
    path('product/<slug>/', ProductDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_from_cart,
         name='remove-single-item-from-cart'),
    path('checkout/',
         ProductCheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/',
         ProductPaymentView.as_view(), name='payment'),
    path('products/category/<slug>',
         get_items_by_category, name='category-filter'),
    path('request-refund/', RefundRequestView.as_view(), name='request-refund'),
    path('profile/', UserProfileView.as_view(), name='profile'),
]

# default: "Django Administration"
admin.site.site_header = 'Jeff Stores'
# default: "Site administration"
admin.site.index_title = 'Jeff Stores Administration'
admin.site.site_title = 'Jeff Stores Admin'  # default: "Django site admin"

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField


LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

LABEL_TAGS = (
    ('N', 'NEW'),
    ('F', 'Featured'),
    ('B', 'bestseller')
)

ADDRESS_TYPE = (
    ('B', 'Billing'),
    ('S', 'Shipping')
)


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=30, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Item(models.Model):
    title = models.CharField(max_length=20)
    price = models.FloatField()
    percentage_discount = models.IntegerField(blank=True, null=True)
    category = models.ForeignKey(Category,
                                 on_delete=models.SET_NULL, null=True, blank=True)
    label_tag = models.CharField(
        choices=LABEL_TAGS, max_length=1, null=True, blank=True)
    label = models.CharField(choices=LABEL_CHOICES,
                             max_length=1, null=True, blank=True)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='items')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:product', kwargs={
            'slug': self.slug
        })

    def get_discount_price(self):
        if self.percentage_discount:
            return round((100 - self.percentage_discount) / 100 * self.price, 2)

    def get_add_to_cart_url(self):
        return reverse('core:add-to-cart', kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse('core:remove-from-cart', kwargs={
            'slug': self.slug
        })

    @property
    def get_image_url(self):
        if self.image:
            return self.image.url
        return '#'


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        if self.item.get_discount_price():
            return round(self.item.get_discount_price() * self.quantity, 2)
        return round(self.item.price * self.quantity, 2)

    def get_amount_saved(self):
        if self.item.get_discount_price():
            return round(self.item.price * self.quantity - self.get_total_item_price(), 2)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, null=True, blank=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, null=True, blank=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, null=True, blank=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, null=True, blank=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.ref_code

    def get_total(self):
        if self.coupon:
            if self.coupon.percentage_discount:
                # apply the percentage discount of the coupon and get the new order total price
                total = sum([price.get_total_item_price()
                             for price in self.items.all()])
                return round((100 - self.coupon.percentage_discount) / 100 * total, 2)
        return sum([price.get_total_item_price() for price in self.items.all()])


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    appartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip_code = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_TYPE)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.street_address

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    percentage_discount = models.IntegerField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.user.username} request {self.pk}"


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='users', blank=True, null=True)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_processing = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} ({self.user.username})"

    @property
    def get_image_url(self):
        if self.photo:
            return self.photo.url
        return '#'


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/footer.html
<!--Footer-->
<footer class="page-footer black text-center font-small mt-4 wow fadeIn">
  <hr class="my-4" />

  <!-- Social icons -->
  <div class="pb-4">
    <a href="https://www.facebook.com/efosa.jeff" target="_blank">
      <i class="fab fa-facebook-f mr-3"></i>
    </a>

    <a href="https://twitter.com/efosa_j" target="_blank">
      <i class="fab fa-twitter mr-3"></i>
    </a>

    <a href="https://github.com/fosajeff" target="_blank">
      <i class="fab fa-github mr-3"></i>
    </a>
  </div>
  <!-- Social icons -->

  <!--Copyright-->
  <div class="footer-copyright py-3">
    ©
    <script>document.write(new Date().getFullYear())</script> Copyright
    <a href="/" target="_blank">

    </a>
  </div>
  <!--/.Copyright-->
</footer>
<!--/.Footer-->

templates/home-page.html
{% extends "base.html" %}

<!-- title -->
{% block head_title %} Home | Jeff Stores {% endblock %}

{% block extra_head %}
<style type="text/css">
  html,
  body,
  header,
  .carousel {
    height: 60vh;
  }

  @media (max-width: 740px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }

  @media (min-width: 800px) and (max-width: 850px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }
</style>
{% endblock %}

{% block content %}

<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <!--First slide-->
    <div class="carousel-item active">
      <div class="view" style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        ">
        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Jeff Stores Shopping Complex</strong>
            </h1>

            <p>
              <strong>Easing shopping, easy life!</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Shop for your most exciting products with ease. Add to cart
                anytime, checkout anytime.</strong>
            </p>

            <a target="_self" href="{% url 'core:products' %}" class="btn btn-outline-white btn-lg">Start Shopping
              <i class="fas fa-shopping-cart ml-2"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/First slide-->

    <!--Second slide-->
    <div class="carousel-item">
      <div class="view" style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        ">
        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Shopping Made Easy</strong>
            </h1>

            <p>
              <strong>Shopping made easy with Jeff Stores!</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Shop for your most exciting products with ease. Add to cart
                anytime, checkout anytime.</strong>
            </p>

            <a target="_blank" href="https:/products" class="btn btn-outline-white btn-lg">Start Shopping
              <i class="fas fa-shopping-cart ml-2"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/Second slide-->

    <!--Third slide-->
    <div class="carousel-item">
      <div class="view" style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        ">
        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Shopping Made Easy</strong>
            </h1>

            <p>
              <strong>Shopping made easy with Jeff Stores!</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Shop for your most exciting products with ease. Add to cart
                anytime, checkout anytime.</strong>
            </p>

            <a target="_blank" href="https:/products" class="btn btn-outline-white btn-lg">Start Shopping
              <i class="fas fa-shopping-cart ml-2"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/Third slide-->
  </div>
  <!--/.Slides-->

  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
  <div class="container">
    <!--Navbar-->
    {% if categories %}
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">
      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">
        <!-- Links -->
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:products' %}">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% for category in categories %}
          {% if category.slug == active_category_slug %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'core:category-filter' category.slug %}">{{ category.name }}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:category-filter' category.slug %}">{{ category.name }}</a>
          </li>
          {% endif %}
          {% endfor %}
        </ul>
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" />
          </div>
        </form>
      </div>
      <!-- Collapsible content -->
    </nav>
    {% endif %}
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">
      <!--Grid row-->
      <div class="row wow fadeIn">
        {% for item in items %}
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4">
          <!--Card-->
          <div class="card">
            <!--Card image-->
            <div class="view overlay">
              <img src="{{ item.get_image_url }}" class="card-img-top" alt="" />
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              {% if item.category %}
              <a href="{% url 'core:category-filter' item.category.slug %}" class="grey-text">
                <h5>{{ item.category }}</h5>
              </a>
              {% endif %}
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                    {% if item.get_label_tag_display %}
                    <span
                      class="badge badge-pill {{ item.get_label_display }}-color">{{ item.get_label_tag_display }}</span>
                    {% endif %}
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                {% if item.get_discount_price %}
                <strong>N{{ item.get_discount_price }}</strong>
                {% else %}
                <strong>N{{ item.price }}</strong>
                {% endif %}
              </h4>
            </div>
            <!--Card content-->
          </div>
          <!--Card-->
        </div>
        <!--Grid column-->
        {% endfor %}
      </div>
    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    {% include "paginator-snippet.html" %}
    <!--Pagination-->
  </div>
</main>
<!--Main layout-->

{% endblock content %}

templates/nav.html
{% load cart_template_tags %}
{% load static %}

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">
    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="{% url 'core:home' %}" target="_self">
      <i style="color:#ff3547" class="fas fa-shopping-cart ml-2"></i>

      <strong class="blue-text">Jeff Stores</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'core:home' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'core:products' %}" target="_self">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'core:checkout' %}" target="_self">Checkout</a>
        </li>
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1">
              {{ request.user | cart_item_count }}
            </span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-sm-inline-block"> Cart </span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'core:profile' %}" class="nav-link waves-effect">
            <span class="clearfix d-sm-inline-block"> Profile </span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'account_logout' %}" class="nav-link waves-effect">
            <span class="clearfix d-sm-inline-block"> Logout </span>
          </a>
        </li>

        {% else %}
        <li class="nav-item">
          <a href="{% url 'account_login' %}" class="nav-link waves-effect">
            <span class="clearfix d-sm-inline-block"> Login </span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'account_signup' %}" class="nav-link waves-effect">
            <span class="clearfix d-sm-inline-block"> Signup </span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- Navbar -->

templates/order-summary.html
{% extends "base.html" %}
{% block extra_head %}
<style>
  #tab1 tr:nth-child(even) {
    background-color: #eee;
  }
</style>
{% endblock extra_head %}
{% block content %}

<!--Main layout-->
<main>
  <div class="container">
    <div class="mt-2">
      <h2 class="mb-3">Order Summary</h2>
      <div class="table-responsive">
        <table class="table" id="tab1">
          <thead>
            <tr style="background-color: #888888;color: #fff;">
              <th scope="col">#</th>
              <th scope="col">Item title</th>
              <th scope="col">Unit Price</th>
              <th scope="col">Quantity</th>
              <th scope="col">Total item price</th>
            </tr>
          </thead>
          <tbody>
            {% for order_item in order.items.all %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>
                <a href="{{ order_item.item.get_absolute_url }}">{{ order_item.item.title }}</a>
              </td>
              <td>
                {% if order_item.item.get_discount_price %}
                <!-- display discount price and amount saved -->
                N {{ order_item.item.get_discount_price }}

                <span class="badge badge-pill secondary-color">Saved N
                  {{ order_item.get_amount_saved }}</span>
                {% else %} N {{ order_item.item.price }}
              </td>
              {% endif %}

              <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i style="color: grey"
                    class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{{ order_item.item.get_add_to_cart_url }}"><i style="color: grey"
                    class="fas fa-plus ml-2"></i></a>
              </td>
              <td>
                N {{ order_item.get_total_item_price }}
                <a href="{{ order_item.item.get_remove_from_cart_url }}"><i style="color: red"
                    class="fas fa-trash float-right"></i></a>
              </td>
            </tr>

            {% empty %}
            <tr>
              <td colspan="5">Your cart is empty</td>
            </tr>
            <tr>
              <td colspan="5">
                <a class="btn btn-primary float-right" href="{% url 'core:products' %}">Continue Shopping</a>
              </td>
            </tr>

            {% endfor %} {% if order.get_total %}
            <tr style="background-color: #fff;">
              <td colspan="4"><strong>Order Total</strong></td>
              <td><strong>N {{ order.get_total }}</strong></td>
            </tr>
            <!-- {% if coupon %}
            {% for code in coupon %}
            <tr style="background-color: #fff;">
              <td colspan="4"><strong>Coupon{{ forloop.counter }}</strong></td>
              <td>
                <strong>{{ code }}</strong>
                <span class="badge badge-pill green ml-1">{{ order.coupon.percentage_discount }}% off</span>
              </td>
            </tr>
            {% endfor %}
            {% endif %} -->
            <tr>
              <td colspan="5">
                <a class="btn btn-warning float-right ml-2 mb-2" href="{% url 'core:checkout' %}">Proceed to
                  Checkout</a>
                <a class="btn btn-info float-right mb-2" href="{% url 'core:products' %}">Continue Shopping</a>
              </td>
            </tr>
            {% endif %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>
<!--Main layout-->

{% endblock content %}

templates/products.html
{% extends "base.html" %} {% block content %}

<!--Main layout-->
<main class="">
  <div class="container">
    <!--Navbar-->
    {% if categories %}
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">
      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">
        <!-- Links -->
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:products' %}">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% for category in categories %}
          {% if category.slug == active_category_slug %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'core:category-filter' category.slug %}">{{ category.name }}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:category-filter' category.slug %}">{{ category.name }}</a>
          </li>
          {% endif %}
          {% endfor %}
        </ul>
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" />
          </div>
        </form>
      </div>
      <!-- Collapsible content -->
    </nav>
    {% endif %}
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">
      <!--Grid row-->
      <div class="row wow fadeIn">
        {% for item in items %}
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4">
          <!--Card-->
          <div class="card">
            <!--Card image-->
            <div class="view overlay">
              <img src="{{ item.get_image_url }}" class="card-img-top" alt="" />
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              {% if item.category %}
              <a href="{% url 'core:category-filter' item.category.slug %}" class="grey-text">
                <h5>{{ item.category }}</h5>
              </a>
              {% endif %}
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                    {% if item.get_label_tag_display %}
                    <span
                      class="badge badge-pill {{ item.get_label_display }}-color">{{ item.get_label_tag_display }}</span>
                    {% endif %}
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                {% if item.get_discount_price %}
                <strong>N{{ item.get_discount_price }}</strong>
                {% else %}
                <strong>N{{ item.price }}</strong>
                {% endif %}
              </h4>
            </div>
            <!--Card content-->
          </div>
          <!--Card-->
        </div>
        <!--Grid column-->
        {% endfor %}
      </div>
    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    {% include "paginator-snippet.html" %}
    <!--Pagination-->
  </div>
</main>
<!--Main layout-->

{% endblock content %}

templates/request-refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}Refund Request{% endblock %} {% block content %}

<main>
    <div class="container">
        <section class="mb-4">
            <div class="row wow fadeIn">
                <div class="col-6 offset-3 pt-5">
                    <h1>Request Refund</h1>

                    <form class="login" method="POST" action="{% url 'core:request-refund' %}">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button class="btn btn-primary" type="submit">
                            Request
                        </button>
                    </form>
                </div>
            </div>
        </section>
    </div>
</main>

{% endblock %}